### ISSUE TITLE
Config update

### ISSUE THREAD

**Issue by kelleydv** [kelleydv/Bapa#4]
[Configuration](https://github.com/kelleydv/Bapa/blob/eed53923b557dc766c2e35d6434dad50d3f61c79/bapa/config/default.cfg) is specified by exporting an environment variable containing the path of the config with something like: `export BAPA_CONF=config/default.cfg`.  Then the application [loads the config](https://github.com/kelleydv/Bapa/blob/eed53923b557dc766c2e35d6434dad50d3f61c79/bapa/__init__.py#L7) from the environment variable.

The default configuration should be loaded automatically, and then _updated_ with anything that may have been specified in a `BAPA_CONF` environment variable.

**Comment by jakiestfu** [comment]
We specify configs based off of environment, not so much the actual config file

**Comment by kelleydv** [comment]
ouutdated
