### ISSUE TITLE
Migrate template engine to Jade

### ISSUE THREAD

**Issue by jakiestfu** [kelleydv/Bapa#8]
Start off with a page or two as an experiment to ensure we can satisfy all needs w/ Jade

**Comment by jakiestfu** [comment]
Successfully converted the layout to jade. https://github.com/kelleydv/Bapa/compare/develop...jakiestfu:pyjade

Should I move forward converting the rest of the pages?

**Comment by kelleydv** [comment]
This is awesome.  I like it.  However, I will not be the primary front-end developer.  I will ask the person who has offered his expertise to take a look.

**Comment by kelleydv** [comment]
I was hopeful when I said I wouldn't be the primary developer...

Closing for now
