### ISSUE TITLE
Move scripts to their own folder or remove

### ISSUE THREAD

**Issue by jakiestfu** [kelleydv/Bapa#9]
With Node, a package.json file kind of implies that there are dependencies. You wouldn't see a shell file in a node project that ends up running `npm install`, just like you wouldn't see a shell file in a python project that ends up running `pip install`. PIP looks for a requirements.txt by default, too, I believe.

Also, for your database, I can see that being a separate script, however, it's still common knowledge to run the database with any website. MySQL runs as a service in lots of projects, so it's kind of always on.

**Comment by kelleydv** [comment]
I thought there might end up being more in those scripts...
Fixed [here](https://github.com/kelleydv/Bapa/commit/46c3093e15005804acf99f40a8c3be2af94fbae4) and [here](https://github.com/kelleydv/Bapa/commit/07bad08e8e956da9c8f23ac38aecf402d293d739)
